apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-nfs
  labels:
    app: media
spec:
  capacity:
    storage: 50Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
#  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /var/nfs/general
    server: 172.31.42.126
