kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: persistentclaim-nfs
  labels:
    app: media
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Mi
#  storageClassName: slow
  selector:
    matchLabels:
      app: media
